위키 항목 신규입력
f-lab-edu/awesome-wiki pull request #19
Opened 2021-05-09 20:10 UTC by neropsys

이슈번호 #11 구현체 풀 리퀘입니다.

그런데 테스트에서 코드상으로 실패할 수 없는 테스트들이 실패하고 있어 원인파악에 어려움이 있습니다ㅠㅠ

잘못 이해한 상태로 테스트코드를 작성한 것으로 생각됩니다. 피드백 요청드립니다.

2021-05-10 17:27 UTC, kmmin78 reviewed
테스트 실패 메세지를 명시해주시면 원인 파악하기 용이할 것 같습니다.
지금 파악된 바로는 service에서 validation 하는 부분이 논리적으로 오류가 있어 보입니다.

2021-05-10 17:27 UTC, kmmin78 commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +            return false
제목이 100자를 넘어가거나 내용이 10,000자를 넘어가면 바로 false를 리턴해야 될 것 같습니다.
현재 조건은 100자를 넘어가면서 내용이 10,000자를 넘어가야 실패하네요.
OR 조건으로 작성하거나, early return pattern으로 긍정 조건으로 작성하면 보기 편할 것 같습니다.

2021-05-11 07:56 UTC, neropsys reviewed
> 테스트 실패 메세지를 명시해주시면 원인 파악하기 용이할 것 같습니다.
> 지금 파악된 바로는 service에서 validation 하는 부분이 논리적으로 오류가 있어 보입니다.

해당 부분을 조건문 테스트하면서 바꾸질 않았네요;; 

![image](https://user-images.githubusercontent.com/4974667/117779196-69c16100-b279-11eb-8a23-b710654c5772.png)


그런데 create안에서 디버그할 때 첫번째 조건문 줄에만 걸리고 이후에는 그냥 넘어가버리는 현상이 있습니다.

그렇다 하더라도 validTitle이 false를 리턴해서 return false가 나와야하고, 해당 조건문에서 어떤 문제로 인해 true가 나오더라도 다음 `if(get(post.title) != null)`에서 결과값이 널이 아니라 false가 리턴되어야하는데 true가 리턴되고 있습니다.

2021-05-11 07:56 UTC, neropsys commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
이 밑으로 모든 테스트들이 실패합니다.
하나씩 주석처리하여 각각의 테스트가 성공하는지 확인했으나 결과가 전부 실패로 나옵니다

2021-05-11 09:06 UTC, kmmin78 commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
올려주신 이미지에 java.lang.NoSuchMethodError가 보이는데, validTitle 함수를 못 찾는 것 같네요.
말씀하시는 걸 보면 step into도 안먹는 것 같은데, 원인을 찾아야 할 것 같습니다.
그 외에 위에 randomPost랑 멤버 변수들이 unresolved 되는 부분도 의심이 갑니다.

2021-05-12 11:55 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +@Suppress("MagicNumber")
여기 Suppress 범위가 너무 넓습니다. 그리고 제목 100자, 본문 10000자 라는 제한은 일종의 정책이라, 말씀하신대로 우선 개발 기간중에는 고정된 값을 사용하는것도 나쁘진 않습니다. 바꾸는게 어렵진 않으니까요.

1. 즉, max title length, max text length 길이 제한 정책을 구현한 어떤 instance 를 주입받고,
2. 그 instance 에 길이 제한을 확인하는 행위를 위임하는 형태로 구현하면
3. 나중에 정책을 DB 나 Redis 에 저장하더라도 PostServiceImpl 을 수정하지 않아도 될 것 같네요.

그리고 이런 경고는 `maxTitleLength`, `maxMainTextLength` 를 static const 로 지정하면 됩니다.

Kotlin 의 `companion object` 기능을 이용해서 아래와 같이 구현할 수 있어요.

```
companion object {
  const val MAX_TITLE_LENGTH = 100
  const val MAX_MAIN_TEXT_LENGTH = 100
}
```

2021-05-12 12:01 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +        if (!validTitle(post) && !validMainText(post) && get(post.title) != null)
지금은 본문 및 제목 길이 정보를 PostService 가 가지고 있는 형태다 보니 validation 을 여기서 담당하는데,

정책을 주입받는 형태로 구현한다면 이렇게 쓸 수도 있을 것 같습니다.

```
if (postLengthPolicy.isPassed(post)) { ... }
```

또는, kotlin 의 `with` 함수와 extension function 기능을 이용해 mix-in 처럼 쓰면 좀 더 읽기 좋은 코드로 바꿀 수도 있습니다.

```
with (postLengthPolicy) {
  if (!post.isLengthCheckPassed()) { ... }
}

// PostLengthPolicy.kt
interface PostLengthPolicy {
  val maxTitleLength: Int
  val maxMainTextLength: Int

  fun Post.isLengthCheckPassed(): Boolean {
    val isTitleLengthCheckPassed = post.title.length < this.maxTitleLength
    val isTextLengthCheckPassed = post.body.length < this.maxMainTextLength

    return isTitleLengthCheckPassed && isTextLengthCheckPassed
  }
}
```

이런 식으로요. 아직 익숙하지 않으시다면, `with` 나 mix-in 구현은 이런것도 있구나 정도로만 보시고, 일단은 간단한 방식으로 한번 바꿔보시죠.

2021-05-12 12:02 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +        if (!validTitle(post) && !validMainText(post) && get(post.title) != null)
길이 제한같은 정책 + validation 의 역할을 PostService 의 역할이 아니라, 별도의 **정책 구현체** 의 역할로 본다면, PostService 는 `Post` 라는 도메인 객체 입출력 및 조립만 담당한다는 본래의 역할만을 좀더 잘 나타내는 응집도 높은 코드가 되겠죠.

2021-05-12 12:03 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +            return false
최소길이 제한 정책은 없나요?

2021-05-12 12:03 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/post/Post.kt
> +    val creator: User
제가 처음 보여드린 데모에서 `val` 로 domain model 의 property 를 선언해서 거기 영향을 받으신 것 같은데, domain object 수정은 어떤 식으로 하실 건지 궁금하네요.

2021-05-12 12:04 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/post/PostImpl.kt
> +class PostImpl constructor(
이런 형태의 값 클래스는 `data class` 를 쓰시면 좀 더 좋습니다. kotlin data class 에 대해서도 한번 검색해서 읽어 보시죠.

2021-05-12 12:19 UTC, FrancescoJo commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
이거 테스트 실패하는 원인 찾아보니깐 구현 오류에요.

```
if (!validTitle(post) && !validMainText(post) && get(post.title) != null)
            return false
```

제목이 잘못되고(AND), 본문이 잘못되고(AND) 제목이 `null` 이 아니면 create 결과: false 라고 구현하셨는데 이게 올바른 구현인지 궁금하네요.

2021-05-12 12:21 UTC, FrancescoJo commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
그리고 테스트 실행시 특정테스트가 어떤 경로로 코드를 실행했는지 빠르게 보시는 방법은 아래 스크린샷을 참고하시기 바랍니다.

1. 테스트 실행 결과 확인
![1](https://user-images.githubusercontent.com/4831238/117973816-ce5ae980-b367-11eb-9c30-930d60d63a6d.png)

2. 실패하는 테스트 fixture 에 대해 'run coverage' 실행
![2](https://user-images.githubusercontent.com/4831238/117973871-ddda3280-b367-11eb-8774-05fa5c2bb382.jpg)

3. 로직 실행경로를 눈으로 확인
![3](https://user-images.githubusercontent.com/4831238/117973895-e3d01380-b367-11eb-9814-e0fdc52b0076.png)

스크린샷 순서대로 실행해 보시면 테스트로직 실행으로 실제 어느 로직을 실행했나를 눈으로 빠르게 확인 가능합니다.

2021-05-12 12:28 UTC, FrancescoJo commented
잘 봤습니다.

부탁드리고 싶은 내용은 아래와 같습니다.

1. PR 본문 Issue template 형식대로 수정해주세요
2. Nested test 작성은 좋습니다. 앞으로도 계속 습관 들여주세요.
3. Test coverage 로 테스트가 실제 의도대로 로직을 타는지 빠르게 확인하는 방법을 코멘트 해 드렸으니 debugger 보다는 coverage 를 이용하시는 편이 디버깅 효율이 좀 더 좋습니다.

그리고 랜덤 데이터 생성기는 우선은 우리가 직접 만들지만, 추후에는 AutoParams 나 네이버의 정상혁님 조직에서 준비중인 jqwik 라이브러리를 이용하면 좀 더 지루한(tedious) 랜덤데이터 생성 노력을 줄일 수 있을 것 같습니다.

2021-05-12 12:28 UTC, FrancescoJo requested changes
Test fail 해결해 주세요.

2021-05-13 08:24 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +            return false
대중적인 위키 서비스(ex. 나무, 위키피디아)의 경우 임시로 빈 페이지만 만들어두는 경우가 있어 최소길이 제한 정책은 만들어두지 않았습니다

2021-05-13 09:45 UTC, neropsys commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
넵
```
if (!validTitle(post) && !validMainText(post) && get(post.title) != null)
            return false
```
이 부분 조건문쪽 디버깅하면서 잘못 지정한 and조건으로 걸어뒀는데 현재는 

```
    override fun create(post: Post): Boolean {
(디버깅 걸리는 줄)
        if (!validTitle(post) || !validMainText(post))
            return false
        if(get(post.title) != null)
            return false

        return postRepository.create(post)
    }
```

이렇게 수정한 상태입니다. 그런데 최적화 옵션같은것이 걸려있는지 괄호로 디버깅 걸리는 줄을 제외하면 바로 콜스택이 바깥으로 넘어가져서 validTitle 메소드 안쪽에 브레이크포인트가 안걸리고 있습니다ㅠ

2021-05-13 13:30 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/post/Post.kt
> +    val creator: User
현재 테스트 시나리오상에는 변경이 필요한 케이스가 없어서 먼저 val로 선언했습니다.
구현로직에 따라 

1. var타입으로 변경
2. 각 멤버 변수들을 받는 copy 생성자

위 방안을 생각하고 있었습니다.

2021-05-13 13:56 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +            return false
그렇군요. 하지만 제목은 최소 길이가 필요하지 않을까요?

2021-05-13 13:58 UTC, FrancescoJo commented on app-core/src/test/kotlin/kr/flab/wiki/core/post/PostServiceTest.kt
> +            fun `등록하는 경우 실패`() {
음 이상하네요 저도 디버거도 한번 써 보고 다시 피드백 드리겠습니다.

2021-05-13 14:03 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/post/Post.kt
> +    val creator: User
네 좋습니다. refactor 까지 생각한다면, 나중에 refactor 하더라도 그 변경 영향범위를 최소화 할 수만 있다면 상관없어요. 
두 방식 모두 좋아보입니다. 참고로 저는 이런 hardcore style 도 가끔 씁니다.

```
interface Post {
  val creator: User
  ..
  val createdAt: LocalDateTime

  fun edit(): PostEditable
}

interface PostEditable: Post {
  override var creator: User
  ..
  override var createdAt: LocalDateTime

  override fun edit() = this
}
```

2021-05-16 12:31 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +            return false
영문의 경우 필요할 것으로 생각되지만 한글의 경우 한글자의 명사가 다수 존재해서 최소 길이를 정한다면 최소 한글자 이상으로 정하는것이 맞을것 같습니다

2021-05-16 14:25 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +        if (!validTitle(post) && !validMainText(post) && get(post.title) != null)
넵 다음 수정 커밋에 적용하도록 하겠습니다

2021-05-17 12:25 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostServiceImpl.kt
> +    private val postLengthPolicy: PostLengthPolicy
이런 코드 아주 좋습니다.

2021-05-17 12:26 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/PostLengthPolicyImpl.kt
> +class PostLengthPolicyImpl(
나중에 Spring 을 쓴다면 여기에 `@Configuration` 같은걸 붙인 뒤, application.yml 에서 읽어들이는 형태로 구성하면,

application.yml 변경만으로도 이제 이 설정을 마음대로 바꿀 수 있게 되겠네요. 아주 좋습니다.

2021-05-17 12:30 UTC, FrancescoJo commented
처음보다 구조가 많이 좋아졌어요. 고생하셨습니다.

#23 작업이랑 중복되는 구조가 있으니, 일단 두 작업 같이 병합 후 제가 한번 구조 가다듬겠습니다.

2021-05-17 12:30 UTC, FrancescoJo approved these changes

2021-05-17 13:16 UTC, kmmin78 approved these changes

2021-05-17 13:17 UTC, merged