use-case의 api 구현
f-lab-edu/awesome-wiki pull request #55
Opened 2021-07-04 23:51 UTC by neropsys

1. 현재까지 작성한 use-case들을 rest api를 통해 접근 가능하도록 구현
1.1 FindDocumentsByTitle
1.2 GetDocumentsByTitle
1.3 SaveDocument
1.4 IsUserEmailExist
1.5 IsUserNameExist
1.6 RegisterUser

이외에도 mysqlRepository까지 구현했습니다

fixes #54

2021-07-06 07:45 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/infrastructure/MySqlDocumentRepository.kt
> +class MySqlDocumentRepository(
좋습니다. 이게 제가 의도했던 거에요. 제가 따로 설명 안했는데 JdbcTemplate 알아서 쓰신것도 좋아요.

2021-07-06 07:46 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/infrastructure/MySqlDocumentRepository.kt
> +        return jdbcTemplate.queryForObject(
이거는 제가 설명 드리지도 않았는데 알아서 spring-jdbc 가져오셨네요. 훌륭합니다. 굿굿.

2021-07-06 07:58 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/Document.kt
> +        val name: String = Document::class.java.simpleName
이 구현의 의도를 잘 모르겠네요

2021-07-06 07:58 UTC, FrancescoJo commented on app-main/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
gradle 의 `runtimeOnly` 는 어떤 의미를 가지나요?

2021-07-06 08:19 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/findDocumentsByTitle/FindDocumentsByTitle.kt
> +class FindDocumentsByTitle(private val documentService: DocumentService) {
Use case 별로 이렇게 구현하는건 좋습니다.

2021-07-06 08:19 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/findDocumentsByTitle/FindDocumentsByTitle.kt
> +    fun onRequest(@RequestParam(value = "title") title: String): MutableList<Document> {
반환타입이 굳이 MutableList 일 필요는 없을 것 같네요.

2021-07-06 08:20 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/saveDocument/SaveDocument.kt
> +        val user = User.newInstance("user", "email", LocalDateTime.now(), LocalDateTime.now())
뒤에 LocalDateTime.now() 를 두번 호출하면 시간대가 미묘하게 다를 것 같아요.
그리고 "user", "email" 문자열을 고정해둔건 아직 current user 를 얻어올 방법이 없어서 그런건가요?

2021-07-06 08:21 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/findDocumentsByTitle/FindDocumentsByTitle.kt
> +@ApiHandler
스프링의 annotation 을 직접 사용하실거라면 제가 선언한 annotation 들은 빼도 됩니다. `@ApiRequest` 등도 마찬가지고요.

2021-07-06 08:23 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/infrastructure/MySqlDocumentRepository.kt
> +        val title = Document::title::name.get()
companion object 에 선언하는 값들은 static 하게 쓸 수 있으니 `TITLE` 처럼 대문자로 바꿔주세요.

그리고 `const val` 과 `val` 의 동작이 다른데 이것도 한번 알아보시는게 좋습니다.

참고로 전자가 조금 더 성능이 좋습니다.

2021-07-06 08:24 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/infrastructure/MySqlDocumentRepository.kt
> +            "select * from User where userName = ?",
딱히 정해진 규칙은 없지만 SQL 문은 소스코드와 구분되게 대문자로 써 주시면 좋겠습니다.
`User` 같은 테이블명도 참조로 바꿔주시면 좋겠네요.

2021-07-06 08:25 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/infrastructure/MySqlDocumentRepository.kt
> +            "insert into ${Document.name}" +
kotlin 에서는 """ 로 multiline string literal 을 쓰실 수 있습니다. 한번 바꿔보시죠. 참고로 Java 15 에서도 지원하고요.

Java 15 의 multiline string 과 kotlin 의 multiline string 은 어떤 차이가 있는지도 한번 알아보시죠 (hint: 성능 관련)

2021-07-06 08:27 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/user/User.kt
> +            return UserEntity(userName, emailAddress, registeredAt, lastActiveAt)
만약 UserEntity 타입에 JPA 같은 외부 의존성이 추가된다면 구현을 core 에 둬야 할까요, 아니면 다른 곳에 둬야 할까요?

2021-07-06 08:28 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/BeanDefinition.kt
> +        @Autowired userRepository: MySqlUserRepository
`@Autowired` 가 나쁜건 아니지만 DI 엔진도 교체의 대상이 될 수도 있으니, 가급적이면 `javax.inject.Inject` 를 쓰시는게 좋겠어요.

2021-07-06 08:28 UTC, FrancescoJo requested changes
몇가지 수정 사항만 확인해 주시면 좋겠습니다. 전반적으로 큰 문제 없습니다. 고생하셨어요.

2021-07-12 17:01 UTC, kmmin78 submitted a review, later dismissed
전체적으로 스프링어노테이션을 능숙하게 잘 쓰신 것 같습니다.
RequestMapping의 속성도 잘 응용하셨고, URI를 상수로 빼서 작업하는 것도 신선했습니다.
고생하셨어요.

2021-07-18 05:44 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/Document.kt
> +        val name: String = Document::class.java.simpleName
일반적인 db 네이밍 규칙과 어울리지 않지만 DB 엔티티 클래스와 테이블의 이름을 일치시키려는 의도로 구현했습니다.

2021-07-18 05:45 UTC, neropsys commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/saveDocument/SaveDocument.kt
> +        val user = User.newInstance("user", "email", LocalDateTime.now(), LocalDateTime.now())
말씀햊쉰대로 현 스펙상 current user를 받아올 방법이 없어 임시로 구현했습니다

2021-07-18 06:07 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/user/User.kt
> +            return UserEntity(userName, emailAddress, registeredAt, lastActiveAt)
core의 경우 개체들의 인터페이스나 상호작용 로직만을 포함해야하므로 다른곳에 둬야합니다.

2021-07-18 06:08 UTC, neropsys commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/BeanDefinition.kt
> +        @Autowired userRepository: MySqlUserRepository
`javax.inject.Inject` 참고하겠습니다

2021-07-18 08:20 UTC, neropsys commented on app-main/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
런타임에서만 사용하는 디펜던시로 컴파일 클래스 경로에는 추가되지 않는 디펜던시입니다

2021-07-18 09:17 UTC, neropsys commented on app-main/src/main/kotlin/kr/flab/wiki/app/api/document/findDocumentsByTitle/FindDocumentsByTitle.kt
> +@ApiHandler
type.annotation의 ApiHandler/Request/Response 말씀이시라면 아직 어떻게 사용해야 RestController, RequestMapping, ApiHandler를 대체 가능한지 이해하지 못한 상황이라 스프링 annotation을 사용했습니다

2021-07-22 12:36 UTC, FrancescoJo approved these changes
좋습니다. 고생하셨습니다.

2021-07-26 07:54 UTC, merged