스프링 시큐리티 및 JWT 사용을 위한 라이브러리 의존성 추가 및 기반 설정 작업
f-lab-edu/awesome-wiki pull request #62
Opened 2021-07-18 12:44 UTC by kmmin78

스프링 시큐리티 및 JWT 사용을 위한 라이브러리 의존성 추가 및 기반 설정 작업

주요 내용

1. 관련 라이브러리 의존성 추가 (spring security, spring boot test, jjwt, restAssured)
2. WebSecurity 설정 , app-core의 도메인 빈 설정.
  -> UserRepository를 빈 설정하기 위해 구현체 클래스 및 팩토리 메서드 생성

기존 PR(https://github.com/f-lab-edu/awesome-wiki/pull/53)은 닫고, 새로 작성한 PR입니다.

Closes #52

2021-07-19 11:49 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/security/WebSecurityConfig.kt
> +    override fun authenticationManagerBean(): AuthenticationManager {
요거, 왠만하면 Bean 선언만 모여있는 별도 파일로 빼는게 좀더 유지보수하기 좋을 것 같습니다.
`@Bean` 이 도처에 널리기 시작하면 나중에 그거 찾는것도 일이니까요.

2021-07-19 11:50 UTC, FrancescoJo requested changes
`@Bean` 선언 외부화

2021-07-22 09:18 UTC, kmmin78 commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/security/WebSecurityConfig.kt
> +    override fun authenticationManagerBean(): AuthenticationManager {
이건 저번 pr에서도 질문을 드렸던 내용인데,
AuthenticationManager을 빈으로 생성하기 위해서는 WebSecurityConfigurerAdapter를 상속 받아야합니다.
WebSecurityConfigurerAdapter를 다른 Configuration 파일에서 또 상속을 받으면, 
다음과 같은 메세지가 뜨면서 스프링이 시작되지 않습니다.
@Order on WebSecurityConfigurers must be unique

짐작컨데, WebSecurityConfigurers는 하나의 Configuration에서만 상속을 받을 수 있다는 건데,
그렇게 되면 authenticationManagerBean은 해당 파일에서만 생성할 수 있게 됩니다.

다른 Bean 설정을 WebSecurityConfig.kt에 모으는 게 나을까요?
아니면, 그대로 유지하는 것 밖에 답이 없을까요?

2021-07-22 12:18 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/security/WebSecurityConfig.kt
> +    override fun authenticationManagerBean(): AuthenticationManager {
```
    override fun authenticationManagerBean(): AuthenticationManager {
        return super.authenticationManagerBean()
    }
```

이 구현을 호출하는 구문을 밖에서 만들어 주면 될 것 같은데요.

즉, 이렇게 구현해 보시면 어떨까요

```
@Configuration
@EnableWebSecurity
class WebSecurityConfig(
    private val authenticationProvider: AuthenticationProvider
) : WebSecurityConfigurerAdapter() {
    override fun authenticationManagerBean(): AuthenticationManager {
        return super.authenticationManagerBean()
    }

    // ...
}

@Configuration
class SomeBeanConfigs {
    @Bean
    override fun authenticationManager(wsConfig: WebSecurityConfig): AuthenticationManager {
        return wsConfig.authenticationManagerBean()
    }
}
```

2021-07-26 14:14 UTC, merged