문서 작성에서 충돌이 발생하는 상황에 대한 예외처리
f-lab-edu/awesome-wiki pull request #65
Opened 2021-07-26 13:53 UTC by neropsys

저번에 use-case 단위 구현과 domain-driven-development에 부합하지 않은 구현체를 올려 이번 구현체에 이해한 대로 구현했습니다.

use-case를 bean으로 등록하고 main 프로젝트에서 api단에 use-case를 사용하도록 했습니다.
그런데 use-case 클래스의 경우 이미 bean으로 등록되어있는 documentRepository를 사용하는데 문제없는 형태인지 궁금합니다.

closes #64

2021-07-26 13:54 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/DocumentServiceImpl.kt
> +            if (it != null && it.version != version) {
여기서 먼저 서버의 최신 버전과 입력으로 들어온 버전이 일치하는지 확인합니다. 수정 창을 띄워놓은 사이에 다른 사용자가 먼저 업데이트를 적용한 경우 이 단계에서 걸러집니다

2021-07-27 08:59 UTC, FrancescoJo commented
음, 현재 구현의 의도는 'Document'Service 처럼 domain object 를 아예 별개의 service 인 것 처럼 구현하는 방식이네요.
마이크로서비스로 확장하긴 좋으나 이렇게 구현할 경우 DocumentService 는 'Document' domain 외의 객체들과 직접 참조를 가지는 형태로 구현하시면 안 됩니다.

객체간의 연결은 의존성이 없는 simple type 또는 양쪽에서 모두 알고있는 key 전용 타입(long, string 등 FK 로 흔히 사용하는 타입) 정도만 사용해서 구현할 수 밖에 없게 될 겁니다. 왜냐면 'Document' domain 이 동작하는 기기와, 'User' domain 이 동작하는 기기가 완전히 달라져 버릴 수도 있기 때문이에요(이기종간 의존성을 지원해 주는 솔루션이 있긴 하지만 특정 솔루션에 구현이 종속되므로 굳이 그런 특별한 경우는 언급하지 않겠습니다).

여담이지만 저는 이번 프로젝트는 그냥 기존의 Controller - Service - Repository 로 구현하되, 'Document'Service 가 아니라 'DocumentWriteService', 'DocumentReadService' 등 'Service' 를 use case 형태로 구현하는 방향이 좋을 것 같다 생각합니다. 왜냐면 추후 MSA 로 분화 같은 시나리오가 생기더라도, 구조를 어떻게 잡건간에 각 use case 들이 서로를 참조하지 않는 형태로 구현 한다면 MSA 로 떼 내는건 그다지 어렵진 않기 때문입니다(오히려 MSA 환경에서는 각 '서비스' 사이의 동작속도 차이, 데이터 동기화, 병렬 처리 효율화 등이 더 큰 이슈긴 합니다). MSA 분리는 나중에 필요하면 그때 가서 고민하는 걸로 하고요.

2021-07-27 09:04 UTC, FrancescoJo commented
그리고 두번째, 질문하신 내용대로 코드가 되어 있지 않아서 혼란스럽습니다만 지향하시는 구조를 보면 Controller - Use case - Service - Repository 의 형태인것 같은데요, 말씀하신 내용은 Onion architecture 의 기본 원칙인 **서로 다음 경계만 바로 참조한다** 를 깨뜨리는 형태가 될겁니다.

경계를 한단계 이상 넘나드는 참조는 좋지 않아요. 참조 흐름이 바로 아랫단계로 내려갈 수 있도록 최대한 단순하게 tiering 을 하시는 편이 좋습니다.

만약 tier 를 한단계 초과해서 참조하는 구현이 나타나게 되면(가령, 예로드신 use case 가 repo 를 바로 참조하는 경우), use case 분리를 위해 service 와 repo 가 모두 줄줄이 딸려와야 하기 때문에 사실상 셋이 한 몸이 되는 형태죠. 결국 제대로된 refactoring 이 불가능해집니다. tier 를 나누는 의미도 퇴색하고요.

2021-07-27 09:07 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/DocumentServiceImpl.kt
> +            if (it != null && it.version != version) {
지금 구현하신 코드의 구조를 저는 Controller - Use case - Service - Repository 의 4 tier 로 이해하고 있는데요,

만약 이게 정말 의도라면 이런 business logic 들은 최대한 use case 로 올리는게 맞을 것 같습니다.

왜냐면 이 로직 재활용할 가능성 별로 안 높을 거거든요. '저장' 이외의 기능에서 제목과 버전을 동시에 체크해야 하는 경우가 생각보다 거의 없을 겁니다. 만약 정말로 4-tier 로 나누신게 의도라면 service 는 cache / db control, message brokering 정도의 기능만 가지는 형태로 역할을 크게 축소하고 단순화 하시는게 좋습니다.

2021-07-27 09:08 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/DocumentServiceImpl.kt
> +            if (it != null && it.version != version) {
구현은 잘 하신것 같아요. wiki product 들이 대부분 이런 식으로 conflict 를 관리하거든요.
그리고 추가로, 지난주에 설명드렸던 'optimistic locking', 'pessimistic locking' 에 대해서도 한번 찾아봐 주세요.

2021-07-27 09:09 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/DocumentServiceImpl.kt
> +                throw DocumentConflictException()
추후에는 여기서 exception 대신 diff 를 띄워주는 로직이 여기 들어온다면 처음 의도했던 친절한 wiki product 가 될 것 같네요.

2021-07-27 09:11 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/PostDocumentUseCaseImpl.kt
> +                println(e)
이런건 주의해주세요. 참고로 println 은 실행 성능을 꽤 잡아먹습니다. 왜 그런지는 https://stackoverflow.com/questions/18584809/java-system-out-effect-on-performance 한번 찬찬히 읽어보시고 저한테 설명해주세요.

2021-07-27 09:12 UTC, FrancescoJo commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/PostDocumentUseCaseImpl.kt
> +                println(e)
그리고 이런경우 log 를 구현할 때 SLF4J 같은걸 이용해서,

```
logger.log("There were {} error found", e) 
```

같은 형태로 구현하는데,

```
logger.log("There were ${e} error found") 
```

로 구현하지 않는 이유에 대해서도 한번 생각해 보시면 좋겠네요.

참고로 이거 대답할 수 있으면 Java 10년차로 인정받으실 수 있는 고급 주제입니다.

2021-07-27 09:15 UTC, FrancescoJo commented
구현에는 큰 문제는 없으나, 4-level Tiering 이 원래 의도하신 형태인지만 확인해 보면 좋겠습니다.

2021-07-29 08:44 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/DocumentServiceImpl.kt
> +            if (it != null && it.version != version) {
> 지금 구현하신 코드의 구조를 저는 Controller - Use case - Service - Repository 의 4 tier 로 이해하고 있는데요,
> 
> 만약 이게 정말 의도라면 이런 business logic 들은 최대한 use case 로 올리는게 맞을 것 같습니다.
> 
> 왜냐면 이 로직 재활용할 가능성 별로 안 높을 거거든요. '저장' 이외의 기능에서 제목과 버전을 동시에 체크해야 하는 경우가 생각보다 거의 없을 겁니다. 만약 정말로 4-tier 로 나누신게 의도라면 service 는 cache / db control, message brokering 정도의 기능만 가지는 형태로 역할을 크게 축소하고 단순화 하시는게 좋습니다.

넵 그럼 이 부분은 usecase쪽으로 올리도록 하겠습니다. 아직 4레벨 구조에서 어떤 로직이 어느 단계에 있는게 어울리는지 감이 좀 부족한 상태인것 같네요ㅠ

2021-07-29 08:53 UTC, neropsys commented on app-core/src/main/kotlin/kr/flab/wiki/core/domain/document/impl/PostDocumentUseCaseImpl.kt
> +                println(e)
아직 로그 관련쪽은 생각칠 못해서 detekt의 exception swallowing을 피하기 위해 println을 사용했었습니다. 로그 세팅도 알아보고 적용하도록 하겠습니다.

2021-07-29 17:33 UTC, neropsys commented
> 만약 tier 를 한단계 초과해서 참조하는 구현이 나타나게 되면(가령, 예로드신 use case 가 repo 를 바로 참조하는 경우), use case 분리를 위해 service 와 repo 가 모두 줄줄이 딸려와야 하기 때문에 사실상 셋이 한 몸이 되는 형태죠. 결국 제대로된 refactoring 이 불가능해집니다. tier 를 나누는 의미도 퇴색하고요.

그렇다면 조금 오버킬일수도 있지만 각 층을 넘나들지 못하도록 use-case와 service, repository도 main과 core가 분리되어있는 것 처럼 프로젝트를 분리하는것은 비효율적일까요?

2021-08-04 10:30 UTC, FrancescoJo commented
> > 만약 tier 를 한단계 초과해서 참조하는 구현이 나타나게 되면(가령, 예로드신 use case 가 repo 를 바로 참조하는 경우), use case 분리를 위해 service 와 repo 가 모두 줄줄이 딸려와야 하기 때문에 사실상 셋이 한 몸이 되는 형태죠. 결국 제대로된 refactoring 이 불가능해집니다. tier 를 나누는 의미도 퇴색하고요.
> 
> 그렇다면 조금 오버킬일수도 있지만 각 층을 넘나들지 못하도록 use-case와 service, repository도 main과 core가 분리되어있는 것 처럼 프로젝트를 분리하는것은 비효율적일까요?

그렇게 하셔도 상관없어요. 오히려 더 좋습니다. `internal` 키워드 빡세게 쓰는 형태가 되겠네요. 저는 좋다고 생각합니다.

2021-08-04 10:31 UTC, FrancescoJo requested changes

2021-08-04 10:31 UTC, FrancescoJo commented on app-main/src/main/kotlin/kr/flab/wiki/app/appconfig/BeanDefinition.kt
> +        @Autowired documentService: DocumentService
여기 굳이 `@Autowired` 없어도 될거에요. 그리고 가급적이면 `javax.inject.Inject` 를 쓰는게 좋습니다.

2021-08-15 00:35 UTC, FrancescoJo approved these changes
고생하셨습니다

2021-08-20 07:48 UTC, merged